# 07 - WORD EMBEDDINGS



* WHAT  : Dense numeric vector representations of words where similar
        meaning words are CLOSE together in vector space.
        e.g. vector("king") - vector("man") + vector("woman") ≈ vector("queen")
        Unlike BoW/TF-IDF (sparse, no meaning captured), embeddings are
        DENSE and capture SEMANTIC relationships.

* WHERE : Recommendation systems, search relevance, chatbots, translation,
        and as the INPUT layer for almost every deep learning NLP model.

* WHY   : TF-IDF has no idea that "good" and "great" are related — they're
        just two different columns. Embeddings place them near each other
        in vector space, letting models generalize/understand synonyms.



# 1. What are World Embeddings ?

A word embedding represents a word as a dense numerical vector that can learn useful relationships and semantic information.

* Bag of Words

TF-IDF

word embedding represent each word as a vector

King   → [0.21, 0.83, 0.14, ...]

Queen  → [0.25, 0.79, 0.18, ...]

Man    → [0.19, 0.72, 0.12, ...]

Woman  → [0.23, 0.75, 0.16, ...]

Words with similar meanings tend to have similar vector representations.

## Why did we need word Embeddings?

* Machine-learning and neural-network models need numerical input, and embeddings provide a more meaningful representation than simple word counts.

Bags of Words

King → [1, 0, 0, 0]

Queen → [0, 1, 0, 0]

It treats them as completely separate words.
## Word Embeddings

King  → vector

Queen → similar vector

The vectors can capture relationships between words.

## MAin Idea

             WORD
               ↓
        Word Embedding
               ↓
       Numerical Vector
               ↓
       Semantic Information

* ex.

"happy"

   ↓

[0.21, 0.54, 0.72, 0.13, ...]

## One-Hot Encoding vs Word Embedding

Before embeddings, we should understand One-Hot Encoding.

Suppose:
["cat", "dog", "king", "queen"]

one-hot-encder representation :

cat   → [1, 0, 0, 0]

dog   → [0, 1, 0, 0]

king  → [0, 0, 1, 0]

queen → [0, 0, 0, 1]

## Simple One-Hot Example 


In [4]:
words = ["cat", "dog", "king", "queen"]

print("One-Hot Encoding")

for i, word in enumerate(words):

    vector = [0] * len(words)

    vector[i] = 1

    print(word, "->", vector)

One-Hot Encoding
cat -> [1, 0, 0, 0]
dog -> [0, 1, 0, 0]
king -> [0, 0, 1, 0]
queen -> [0, 0, 0, 1]


## Word Embedding with Keras

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()

model.add(
    Embedding(
        input_dim=10,
        output_dim=4
    )
)

model.build()

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## Using Keras Tokenizer

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I love Python",
    "I love NLP",
    "Python is easy",
    "NLP is interesting"
]

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'i': 1, 'love': 2, 'python': 3, 'nlp': 4, 'is': 5, 'easy': 6, 'interesting': 7}


## Complete simple embedding example

In [1]:
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding


print("=" * 60)
print("WORD EMBEDDINGS")
print("=" * 60)


# --------------------------------------------------
# Sample sentences
# --------------------------------------------------

sentences = [
    "I love Python",
    "I love NLP",
    "Python is easy",
    "NLP is interesting"
]


# --------------------------------------------------
# 1. Convert words into numbers
# --------------------------------------------------

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

print("\nWord Index:")
print(tokenizer.word_index)


# --------------------------------------------------
# 2. Convert sentences into sequences
# --------------------------------------------------

sequences = tokenizer.texts_to_sequences(sentences)

print("\nSequences:")
print(sequences)


# --------------------------------------------------
# 3. Find vocabulary size
# --------------------------------------------------

vocab_size = len(tokenizer.word_index) + 1

print("\nVocabulary Size:")
print(vocab_size)


# --------------------------------------------------
# 4. Make all sentences same length
# --------------------------------------------------

padded_sequences = pad_sequences(
    sequences,
    padding="post"
)

print("\nPadded Sequences:")
print(padded_sequences)


# --------------------------------------------------
# 5. Create Embedding Layer
# --------------------------------------------------

embedding_size = 5

model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_size
    )
)

model.build(
    input_shape=(None, padded_sequences.shape[1])
)


# --------------------------------------------------
# 6. Display model
# --------------------------------------------------

print("\nModel:")
model.summary()


# --------------------------------------------------
# 7. Generate embeddings
# --------------------------------------------------

embeddings = model.predict(
    padded_sequences,
    verbose=0
)

print("\nEmbedding Shape:")
print(embeddings.shape)


# --------------------------------------------------
# 8. Display embedding
# --------------------------------------------------

print("\nEmbedding Values:")
print(embeddings)

WORD EMBEDDINGS

Word Index:
{'i': 1, 'love': 2, 'python': 3, 'nlp': 4, 'is': 5, 'easy': 6, 'interesting': 7}

Sequences:
[[1, 2, 3], [1, 2, 4], [3, 5, 6], [4, 5, 7]]

Vocabulary Size:
8

Padded Sequences:
[[1 2 3]
 [1 2 4]
 [3 5 6]
 [4 5 7]]

Model:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 5)           │            40 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)


Embedding Shape:
(4, 3, 5)

Embedding Values:
[[[-0.03943393  0.00311079 -0.02495781 -0.01892601  0.03263569]
  [-0.02971171 -0.01216389  0.04263121  0.04381112 -0.02617021]
  [-0.00863324  0.03822483 -0.03591483  0.03095272  0.02414949]]

 [[-0.03943393  0.00311079 -0.02495781 -0.01892601  0.03263569]
  [-0.02971171 -0.01216389  0.04263121  0.04381112 -0.02617021]
  [ 0.00364984 -0.03186373 -0.0309878   0.00634701 -0.01486257]]

 [[-0.00863324  0.03822483 -0.03591483  0.03095272  0.02414949]
  [-0.02042962  0.00470687  0.00729422 -0.04609597 -0.00616766]
  [-0.03771903 -0.03017663  0.02681638  0.04015699  0.00779995]]

 [[ 0.00364984 -0.03186373 -0.0309878   0.00634701 -0.01486257]
  [-0.02042962  0.00470687  0.00729422 -0.04609597 -0.00616766]
  [ 0.0116093   0.02615667 -0.00238894  0.02933682  0.03973376]]]


## Understand the complete flow

Raw Text

   ↓

"I love Python"

   ↓

Tokenizer

   ↓

[1, 2, 3]

   ↓

Padding

   ↓

[1, 2, 3]

   ↓

Embedding Layer

   ↓
   
[0.12, 0.45, 0.21, 0.63, 0.17]

* Raw Text

   ↓

"I love Python"

   ↓

Tokenizer

   ↓


[1, 2,
  3]

   ↓

Padding

   ↓

[1, 2, 3]

   ↓

Embedding 

   ↓

[0.12, 0.45, 0.21, 0.63, 0.17]